### ISSUE TITLE
DLF URL on Credits page

### ISSUE THREAD

**Issue by nowviskie** [nimbletents/nimbletents.github.io#3]
https://www.diglib.org/ would be a better URL than the one to a description of us on CLIR's page! (sorry things are too crazy right now to fix this in a pull request...)

**Comment by elotroalex** [comment]
Fixed. Pushing soon. First trying to redo my deployment strategy. That day I had to whip up something 4 hours ahead of schedule. You know, for a change. Lol.

**Comment by elotroalex** [comment]
& thank you for everything! I still can't believe you had time to put in a ticket!

**Comment by nowviskie** [comment]
Thank _you!_ Looking forward to talking more with you about this soon!
