### ISSUE TITLE
power

### ISSUE THREAD

**Issue by giannetti** [nimbletents/nimbletents.github.io#5]
Here's an irony, given that PR is even still mostly without... But the spaces at my institution are not the most modern, and it didn't occur to me until after the event started that people needed to plug in. Fortunately, we were able to scrounge some power strips and extension cords at the last minute, but it would be wise to plan ahead if the reserved space doesn't have many outlets. This consideration might be added to the **Rooms** bullet point under _Laying the Foundation_.

**Comment by elotroalex** [comment]
good call! getting to it soon

**Comment by giannetti** [comment]
Dawn includes this issue in her "Planning a Mapathon" doc in the Gdrive resources, so maybe not absolutely critical to mention here.

**Comment by elotroalex** [comment]
good catch. changed anyway :)
